# Generated by Django 2.0.3 on 2018-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partySize', models.IntegerField()),
                ('partyNames', models.TextField()),
                ('allergy', models.TextField()),
                ('speacialRequest', models.TextField()),
            ],
        ),
    ]
