# Generated by Django 2.0.3 on 2018-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='allergy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='speacialRequest',
            field=models.TextField(blank=True),
        ),
    ]
